version: 2
updates:
  - package-ecosystem: "yarn" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00" # UTC
