name: Que Faire de Mes Déchets | CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: npm test
      - run: npm run build --if-present
